#!/bin/bash
if [ -f "/usr/bin/figlet" ] | [ -f "/bin/figlet" ];
then
figlet we are setting good your system 
fi
if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q /usr/share/applications
  fi
  if [ -x /usr/bin/update-menus ]; then
    update-menus
  fi
figlet francis guru say goodbye
