.\" Manpage for mediaplayer.
.\" Contact francismboya3@gmail.com. mediaplayer foundation personel in to correct errors or typos.
.TH man 8 "19 May 2020" "1.0" "mediaplayer man page"
.SH NAME
mediaplayer \- play audio and video \.mp4 and \.mp3

.SH SYNOPSIS
mediaplayer 
.SH DESCRIPTION
mediaplayer founded by university student called francis mboya, he is a linux script writer .  On Debian, user should usually use mediaplayer because it can't
overhead system resources.
use mediaplayer for better performance and reward

.SH OPTIONS
mediaplayer [NO OPTION]
     press enter then wait for input dialog to appear, once it appear enter 
         1 to select multiple video and audio file file and will play automatic for you
         2 to select directory mediaplayer will play audio or video of your choice
         3 to allow mediaplayer to search all audio and video file found on your home directory finally it will play it for you\n\n
\n
\-\-others
   CTR\+C to stop mediaplayer 
   CTR\+Z to run mediaplayer on background

.SH MISLEARN
user are failed to stop  mediaplayer because the use wrong procedure\n
\n
to close minimize player window then press CTR\+C

.SH SEE ALSO
zenity, mplayer, dialog
.SH BUGS
No bugs reported media player work fine.

.SH AUTHOR
Mr francis mboya (francismboya3@gmail.com)
